version: '3.8'
name: exec

services:
  sandbox:
    build: .
    image: exec-sandbox:latest
    networks:
      - no-internet
    restart: unless-stopped
    environment:
      - EXEC_PORT=3000
      - EXEC_KEY=b01a143d-937f-4a8d-97bf-a2f3ecbb3d3f
    deploy:
      restart_policy:
        condition: any
        delay: 1h
        max_attempts: 0
        window: 0s

  nginx:
    image: nginx:latest
    networks:
      - normal
      - no-internet
    restart: unless-stopped
    ports:
      - "3414:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  normal:
    driver: bridge
  no-internet:
    internal: true
